var projectSeeds = [
 {
	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
 },
 {
 	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
 },
 {
 	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
},
{
	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
},
{
	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
},
{
	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
},
{
	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
},
{
	'name' : 'Roca Lisa',
	'thumb' : '/images/RosaLisaThumb.jpg',
	'location' : 'Ibiza, Spain',
	'description' : 'A modern villa located on the island of Ibiza. The architecture combines contemporary elements with natural materials. The interior flows onto outdoor terraces capturing views of the Mediterranean.',
	'status' : 'Completed 2014',
	'siteArea' : '2208m',
	'projectArea': '845m',
	'type' : 'Single Residential',
}
]